# Manejo numérico con librería numpy
NumPy es una biblioteca en Python que proporciona operaciones numéricas rápidas y
eficientes con arrays. Se usa ampliamente en ciencia de datos para realizar operaciones
matemáticas con grandes conjuntos de datos.

## Listas de python y numpy
Las arrays(listas) en NumPy son similares a las listas de Python, pero son más eficientes y pueden
realizar operaciones más rápido. Las arrays en Numpy son homogéneas, lo que significa
que solo pueden contener elementos del mismo tipo de datos, mientras que las listas de
Python pueden contener elementos de diferentes tipos de datos. Los arrays en NumPy
también tienen un tamaño fijo, mientras que las listas de Python no. Los arrays en Numpy
pueden ser N dimensionales.

![](https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png)

## Instalación de numpy

In [1]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/32/95/908d0caa051beae4f7c77652dbbeb781e7b717f3040c5c5fcaed4d3ed08f/numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 682.7 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 821.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   -- ------------------------------------- 1.1/15.5 MB 23.3 MB/s eta 0:00:01
   --------- ------------------------------ 3.6/15.5 MB 38.0 MB/s eta 0:00:01
   -------------- ------------------------- 5.7/15.5 MB 45.6 MB/s eta 0:00:01
   --------------------- ------------------ 8.4/15.5 MB 44.6 MB/s eta 0:00:01
   ----------------------------- ---------- 11.3/15.5 MB 59.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.5 MB 59.5 MB/s eta 0:00:01
   --------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.__version__

[1,2,3] * 2
np.array([1,2,3]) * 2
np.array([1,2,3]) + 2 #SIEMPRE EJECUTA EL ÚLTIMO

array([3, 4, 5])

### CREACIÓN DE UN ARRAY EN NUMPY



In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
print("a:", a)

b = np.zeros(2, dtype=int) #1er parametro, cantidad, 2do parametro, tipo de dato
print("b:", b)

c = np.ones(6, dtype=float)
print("c:", c)

d = np.random.rand(3)
print("d:", d)

e = np.arange(0, 11, step=5)
print("e:", e)

f = np.linspace(1, 10, 7) #inicio, fin, cantidad de números
print("f:", f)

a: [1 2 3 4 5 6]
b: [0 0]
c: [1. 1. 1. 1. 1. 1.]
d: [0.62610653 0.97094519 0.42353567]
e: [ 0  5 10]
f: [ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [16]:
g = np.array([[1,2,3],[2,4,6]]) #IGAL A MATRIX() //sin embargo, este obliga a que sea si o si de 2 dimsensiones
print(g)
print(g.shape)

[[1 2 3]
 [2 4 6]]
(2, 3)


### DIMENSIÓN Y REDIMENSIONAMIENTO


In [73]:
h_prima = a
h = a.reshape(3,2) #"a" era de 1 dimension, pero ahora lo estamos cambiando a 2 dimensiones
print(h_prima)
print(h)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [30]:
h.flatten() #"h" estaba en 2 dimensiones, pero ahora con flatten lo ponemos en una dimension, NO MODIFICA EL ARREGLO ORIGINAL

array([1, 2, 3, 4, 5, 6])

In [49]:
i = h.transpose()
print(h)
i.shape
print("====================")
print(i) #Realiza la Transpuesta
print("====================")

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### EXPANDIR Y COMPRIMIR ARRAYS

In [21]:
#EXPANSIÓN
print("a:",a)
a_expandido = np.expand_dims(a, axis = 1) #Crea una dimension más
print("a_expandido:",a_expandido)
a_expandido.shape

a: [1 2 3 4 5 6]
a_expandido: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [22]:
#COMPRESION
np.squeeze(a_expandido) #Lo convierte en una dimension menos (la original)

array([1, 2, 3, 4, 5, 6])

### INDICES Y SLICE
![](https://scipy-lectures.org/_images/numpy_indexing.png)

In [27]:
#[inicio:fin:pasos]
#[start:end:steps]
array_ej_1 = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
#array_ej_1[3:8]
array_ej_1[2::2]


array([ 30,  50,  70,  90, 110])

In [35]:
# [INICIO:FIN:PASOS,INICIO:FIN:PASOS]

array_ej_2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(array_ej_2)
prueba = array_ej_2[1:, 1:]
print(prueba)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]


### APILAR Y CONCATENAR

In [12]:
#APILAMIENTO

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
print("Apilar verticalmente")
verticalmente = np.vstack((array_1, array_2))
print(verticalmente)
print(verticalmente.shape)
print("Aplicar horizontalmente")
horizontalmente = np.hstack((array_1, array_2))
print(horizontalmente)
print(horizontalmente.shape)

#CONCATENACIÓN

array_3 = np.array([[1,2], [3,4]])
print(array_3)
array_4 = np.array([[5,6], [7,8]])
print(array_4)
print("CONCATENAR EJE 0")
concatenacion_eje_0 = np.concatenate((array_3, array_4), axis = 0)
print(concatenacion_eje_0)
print("CONCATENAR EJE 1")
concatenacion_eje_1 = np.concatenate((array_3, array_4), axis = 1)
print(concatenacion_eje_1)

Apilar verticalmente
[[1 2 3]
 [4 5 6]]
(2, 3)
Aplicar horizontalmente
[1 2 3 4 5 6]
(6,)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
CONCATENAR EJE 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
CONCATENAR EJE 1
[[1 2 5 6]
 [3 4 7 8]]


### BROADCASTING
Es una característica poderosa en NumPy que nos permite realizar operaciones aritméticas
en matrices de diferentes dimensiones.

In [21]:
array_5 = np.array([[1,2,3], [3,4,5]])
array_6 = np.array([[7,8,9], [10,11,12]])
print(array_5)
print(array_6)
print("=================")
print(array_5 + array_6)
print("=================")
print(array_5 * array_6)
print("=================")


[[1 2 3]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [13 15 17]]
[[ 7 16 27]
 [30 44 60]]


### UNIVERSAL FUNCTIONS
NumPy proporciona una amplia gama de funciones universales que se pueden aplicar los
arrays para realizar operaciones matemáticas. Algunas funciones son:

- `np.add`: suma dos arrays por elementos
- `np.subtract`: resta dos arrays por elementos
- `np.multiply`: multiplica dos arrays por elementos
- `np.divide`: divide dos arrays por elementos
- `np.abs`: calcula el valor absoluto de un array
- `np.sin`: calcula el seno de un array
- `np.cos`: calcula el coseno de un array
- `np.exp`: calcula el exponente de un array

In [30]:
array_7 = np.array([1,2,3])
array_8 = np.array([4,5,6])
print("SUMA: \t", np.add(array_7, array_8))
print("DIVISIÓN: \t", np.divide(array_7, array_8))
resta = np.subtract(array_7, array_8)
print("RESTA: \t", resta)
print("ABS: \t", np.abs(resta))
print("SIN: \t", np.sin(array_7))
print("COS: \t", np.cos(array_7))
print("EXP: \t", np.exp(array_7))

SUMA: 	 [5 7 9]
DIVISIÓN: 	 [0.25 0.4  0.5 ]
RESTA: 	 [-3 -3 -3]
ABS: 	 [3 3 3]
SIN: 	 [0.84147098 0.90929743 0.14112001]
COS: 	 [ 0.54030231 -0.41614684 -0.9899925 ]
EXP: 	 [ 2.71828183  7.3890561  20.08553692]


### FUNCIONES MATEMÁTICAS
NumPy proporciona muchas funciones para realizar operaciones matemáticas en arrays:

- `np.mean`: calcula la media de un array
- `np.median`: calcula la mediana de un array
- `np.std`: calcula la desviación estándar de un array
- `np.min`: calcula el valor mínimo de un array
- `np.max`: calcula el valor máximo de un array
- `np.argmin`: Calcula el índice del valor mínimo de un array
- `np.argmax`: Calcula el índice del valor máximo de un array
- `np.sort`: Ordena un array en orden ascendente


In [39]:
notas = np.array([10,5,12,15,8,20,19,13])
print("PROMEDIO: \t", np.mean(notas))
print("MEDIANA: \t", np.median(notas))
print("DESVIACIÓN STANDAR: \t", np.std(notas))
print("MINIMO: \t", np.min(notas))
print("MAXIMO: \t", np.max(notas))
print("INDICE MINIMO: \t", np.argmin(notas))
print("INDICE MAXIMO: \t", np.argmax(notas))
print("ORDEN ASCENDENTE: \t", np.sort(notas))


PROMEDIO: 	 12.75
MEDIANA: 	 12.5
DESVIACIÓN STANDAR: 	 4.841229182759271
MINIMO: 	 5
MAXIMO: 	 20
INDICE MINIMO: 	 1
INDICE MAXIMO: 	 5
ORDEN ASCENDENTE: 	 [ 5  8 10 12 13 15 19 20]


## Ejercicios:
1.- Cree un array en NumPy de 10 ceros.

In [36]:
cero = np.zeros(10, dtype=int)
print("cero:", cero)

cero: [0 0 0 0 0 0 0 0 0 0]


2.- Cree un array en NumPy de 10 unos.

In [37]:
uno = np.ones(10, dtype=int)
print("uno:", uno)

uno: [1 1 1 1 1 1 1 1 1 1]


3.- Cree un array NumPy de 10 números aleatorios entre 0 y 1.

In [39]:
aleatorio = np.random.rand(10) #parametro: cantidad de números
print("aleatorio:", aleatorio)

aleatorio: [0.72465088 0.400727   0.00838917 0.60346963 0.38221374 0.29921816
 0.50325074 0.31122318 0.5875751  0.27283072]


4.- Cree un array NumPy de 10 números espaciados uniformemente entre 0 y 1.

In [40]:
espaciado = np.linspace(0, 1, 10) #inicio, fin, cantidad de números
print("espaciado:", espaciado)

espaciado: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


5.- Obtenga las dimensiones y la forma de la matriz NumPy de la pregunta 3. 

In [50]:
dimension = aleatorio
print(dimension.shape)

(10,)


6.- Modifique la matriz NumPy de la pregunta 3 en un 2x5 matriz. 

In [51]:
modificar = aleatorio.reshape(2,5)
print(modificar)

[[0.72465088 0.400727   0.00838917 0.60346963 0.38221374]
 [0.29921816 0.50325074 0.31122318 0.5875751  0.27283072]]


7.- Aplane la matriz NumPy de la pregunta 3. 

In [52]:

aplanar = np.squeeze(aleatorio)
print(aplanar)


[0.72465088 0.400727   0.00838917 0.60346963 0.38221374 0.29921816
 0.50325074 0.31122318 0.5875751  0.27283072]


8.- Transponga la matriz NumPy de la pregunta 3. 

In [54]:
transponer = aleatorio.transpose()
print(transponer)
transponer.shape


[0.72465088 0.400727   0.00838917 0.60346963 0.38221374 0.29921816
 0.50325074 0.31122318 0.5875751  0.27283072]


(10,)

9.- Expanda la matriz NumPy de la pregunta 3 agregando una nueva dimensión.

In [58]:
expandir = np.expand_dims(aleatorio, axis = 1)
print(expandir)

[[0.72465088]
 [0.400727  ]
 [0.00838917]
 [0.60346963]
 [0.38221374]
 [0.29921816]
 [0.50325074]
 [0.31122318]
 [0.5875751 ]
 [0.27283072]]


10.- Comprima la matriz NumPy de la pregunta 9.

In [59]:
comprimir = np.squeeze(expandir)
print(comprimir)

[0.72465088 0.400727   0.00838917 0.60346963 0.38221374 0.29921816
 0.50325074 0.31122318 0.5875751  0.27283072]


11.- Cree en NumPy un array de números 10 aleatorios enteros entre 0 y 100.

In [61]:
aleatorio_100 = np.random.randint(0,100,10) #parametro: cantidad de números
print("aleatorio_100:", aleatorio_100)

aleatorio_100: [62 78 36 61 41 18 58 40 47 37]


12.- Corte el array NumPy de la pregunta 11 para obtener los elementos en el índice 2,
5 y 8.

In [62]:


nuevo_array = aleatorio_100[2::3]
print(nuevo_array)

[36 18 47]


13.- Cree una matriz de 2 x 5 de números enteros aleatorios entre 0 y 100.

In [74]:
matriz_aleatoria = np.random.randint(0, 100, size=(2, 5))
print(matriz_aleatoria)

[[ 1 97  9 63 64]
 [77  3 21 48 93]]


14.- Corte la matriz de la pregunta 13 para obtener los elementos de la segunda fila. 

15.- Una las matrices NumPy de las preguntas 11 y 13 a lo largo del eje vertical.

16.- Cree una matriz de `shape (3,3,3)` de números enteros aleatorios entre 0 y 100.


17.- Corte la matriz de la pregunta 16 para obtener los elementos en el segundo plano,
la primera fila y la tercera columna. 

18.- Realice sumas, restas, multiplicaciones y divisiones por elementos en la matriz
NumPy de la pregunta 11 y la matriz de la pregunta 13. 

19.- Calcule la media, la mediana y la desviación estándar de la matriz NumPy de la
pregunta 11.

20.- Encuentre los valores mínimo y máximo y sus índices en la matriz NumPy de la
pregunta 11.

21.- Cree una matriz NumPy de 10 enteros aleatorios entre 0 y 100 y reemplace todos
los números pares con 0. 

22.- Cree una matriz de 5x5 de enteros aleatorios entre 0 y 100 y reemplace todos los
elementos que son divisibles por 3 con 0.

23.- Realice funciones trigonométricas por elementos (sen, cos, tan) en la matriz
NumPy de la pregunta 1.

24.- Cree una matriz de 2x5 de números enteros aleatorios entre 0 y 100 y realice
operaciones de comparación de elementos (mayor que, menor que, igual a) con un
valor escalar. 

25.- Cree una matriz de 3x3x3 de números enteros aleatorios entre 0 y 100 y realice
operaciones lógicas por elementos (si es igual) con un valor escalar. 

26.- Cree un array de 10 números enteros aleatorios entre 0 y 100 y ordénelo en orden
ascendente.

27.- Cree una matriz de 5x5 de números enteros aleatorios entre 0 y 100 y ordene las
filas en orden ascendente.

28.- Cree una matriz de 3x3x3 de números enteros aleatorios entre 0 y 100 y ordene en
función del axis 2 (planos) en orden ascendente.