# Manejo numérico con librería numpy
NumPy es una biblioteca en Python que proporciona operaciones numéricas rápidas y
eficientes con arrays. Se usa ampliamente en ciencia de datos para realizar operaciones
matemáticas con grandes conjuntos de datos.

## Listas de python y numpy
Las arrays(listas) en NumPy son similares a las listas de Python, pero son más eficientes y pueden
realizar operaciones más rápido. Las arrays en Numpy son homogéneas, lo que significa
que solo pueden contener elementos del mismo tipo de datos, mientras que las listas de
Python pueden contener elementos de diferentes tipos de datos. Los arrays en NumPy
también tienen un tamaño fijo, mientras que las listas de Python no. Los arrays en Numpy
pueden ser N dimensionales.

![](https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png)

## Instalación de numpy

In [1]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/32/95/908d0caa051beae4f7c77652dbbeb781e7b717f3040c5c5fcaed4d3ed08f/numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 320.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 324.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 1.7 MB/s eta 0:00:09
   ------------ --------------------------- 4.8/15.5 MB 50.7 MB/s eta 0:00:01
   -------------------------- ------------- 10.3/15.5 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------  15.4/15.5 MB 110.0 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 110.0 MB/s eta 0:00:01
   ----------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### CREACIÓN DE UN ARRAY EN NUMPY



In [26]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print("a:",a)

b = np.zeros(2, dtype=int)
print("b:",b)

c = np.ones(6, dtype=int)
print("c:",c)

d = np.random.rand(3)
print("d:",d)

e = np.arange(0, 11, step = 5)
print("e:",e)

f = np.linspace(1, 10, 7)
print("f:",f)

a: [1 2 3 4 5 6]
b: [0 0]
c: [1 1 1 1 1 1]
d: [0.82088983 0.66333339 0.60487212]
e: [ 0  5 10]
f: [ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [22]:
g = np.array([[1,2,3],[2,4,6]]) #IGAL A MATRIX()
print(g.shape)

(2, 3)


### DIMENSIÓN Y REDIMENSIONAMIENTO


In [29]:
h = a.reshape(2,3)
print(h)

[[1 2 3]
 [4 5 6]]


In [30]:
h.flatten()

array([1, 2, 3, 4, 5, 6])

In [32]:
i = h.transpose()
i.shape

(3, 2)

### EXPANDIR Y COMPRIMIR ARRAYS

In [36]:
#EXPANSIÓN
print("a:",a)
a_expandido = np.expand_dims(a, axis = 1)
print("a_expandido:",a_expandido)
a_expandido.shape

#COMPRESION
#np.squeeze("")

a: [1 2 3 4 5 6]
a_expandido: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

### INDICES Y SLICE
![](https://scipy-lectures.org/_images/numpy_indexing.png)

In [39]:
#[inicio,fin,pasos]
#[start,end,steps]
array_ej_1 = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
#array_ej_1 = []
array_ej_1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

### APILAR Y CONCATENAR

### BROADCASTING
Es una característica poderosa en NumPy que nos permite realizar operaciones aritméticas
en matrices de diferentes dimensiones.

### UNIVERSAL FUNCTIONS
NumPy proporciona una amplia gama de funciones universales que se pueden aplicar los
arrays para realizar operaciones matemáticas. Algunas funciones son:

- `np.add`: suma dos arrays por elementos
- `np.subtract`: resta dos arrays por elementos
- `np.multiply`: multiplica dos arrays por elementos
- `np.divide`: divide dos arrays por elementos
- `np.abs`: calcula el valor absoluto de un array
- `np.sin`: calcula el seno de un array
- `np.cos`: calcula el coseno de un array
- `np.exp`: calcula el exponente de un array

### FUNCIONES MATEMÁTICAS
NumPy proporciona muchas funciones para realizar operaciones matemáticas en arrays:

- `np.mean`: calcula la media de un array
- `np.median`: calcula la mediana de un array
- `np.std`: calcula la desviación estándar de un array
- `np.min`: calcula el valor mínimo de un array
- `np.max`: calcula el valor máximo de un array
- `np.argmin`: Calcula el índice del valor mínimo de un array
- `np.argmax`: Calcula el índice del valor máximo de un array
- `np.sort`: Ordena un array en orden ascendente


## Ejercicios:
1.- Cree un array en NumPy de 10 ceros.

2.- Cree un array en NumPy de 10 unos.

3.- Cree un array NumPy de 10 números aleatorios entre 0 y 1.

4.- Cree un array NumPy de 10 números espaciados uniformemente entre 0 y 1.

5.- Obtenga las dimensiones y la forma de la matriz NumPy de la pregunta 3. 

6.- Modifique la matriz NumPy de la pregunta 3 en un 2x5 matriz. 

7.- Aplane la matriz NumPy de la pregunta 3. 

8.- Transponga la matriz NumPy de la pregunta 3. 

9.- Expanda la matriz NumPy de la pregunta 3 agregando una nueva dimensión.

10.- Comprima la matriz NumPy de la pregunta 9.

11.- Cree en NumPy un array de números 10 aleatorios enteros entre 0 y 100.

12.- Corte el array NumPy de la pregunta 11 para obtener los elementos en el índice 2,
5 y 8.

13.- Cree una matriz de 2 x 5 de números enteros aleatorios entre 0 y 100.

14.- Corte la matriz de la pregunta 13 para obtener los elementos de la segunda fila. 

15.- Una las matrices NumPy de las preguntas 11 y 13 a lo largo del eje vertical.

16.- Cree una matriz de `shape (3,3,3)` de números enteros aleatorios entre 0 y 100.


17.- Corte la matriz de la pregunta 16 para obtener los elementos en el segundo plano,
la primera fila y la tercera columna. 

18.- Realice sumas, restas, multiplicaciones y divisiones por elementos en la matriz
NumPy de la pregunta 11 y la matriz de la pregunta 13. 

19.- Calcule la media, la mediana y la desviación estándar de la matriz NumPy de la
pregunta 11.

20.- Encuentre los valores mínimo y máximo y sus índices en la matriz NumPy de la
pregunta 11.

21.- Cree una matriz NumPy de 10 enteros aleatorios entre 0 y 100 y reemplace todos
los números pares con 0. 

22.- Cree una matriz de 5x5 de enteros aleatorios entre 0 y 100 y reemplace todos los
elementos que son divisibles por 3 con 0.

23.- Realice funciones trigonométricas por elementos (sen, cos, tan) en la matriz
NumPy de la pregunta 1.

24.- Cree una matriz de 2x5 de números enteros aleatorios entre 0 y 100 y realice
operaciones de comparación de elementos (mayor que, menor que, igual a) con un
valor escalar. 

25.- Cree una matriz de 3x3x3 de números enteros aleatorios entre 0 y 100 y realice
operaciones lógicas por elementos (si es igual) con un valor escalar. 

26.- Cree un array de 10 números enteros aleatorios entre 0 y 100 y ordénelo en orden
ascendente.

27.- Cree una matriz de 5x5 de números enteros aleatorios entre 0 y 100 y ordene las
filas en orden ascendente.

28.- Cree una matriz de 3x3x3 de números enteros aleatorios entre 0 y 100 y ordene en
función del axis 2 (planos) en orden ascendente.